services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 228322
      MYSQL_DATABASE: example
      MYSQL_USER: localhost
      MYSQL_PASSWORD: 228322
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql
  back:
    build: ./
    command: bash -c "python manage.py wait 20 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/back
    ports:
      - '8000:8000'
    depends_on:
      - db
