# Generated by Django 5.0.2 on 2025-04-19 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearMetaCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('hire_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Набор (кол-во студентов)')),
            ],
            options={
                'verbose_name': 'Мета-информация по годам для компании',
                'verbose_name_plural': 'Мета-информация по годам для компаний',
                'db_table': 'practice_yearmetacompany',
                'managed': False,
            },
        ),
    ]
