# Generated by Django 5.0.2 on 2025-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'university_faculty',
                'managed': False,
            },
        ),
    ]
