# Generated by Django 5.0.2 on 2025-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRepresentativeProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=512, null=True)),
                ('messenger', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'auths_companyrepresentativeprofile',
                'managed': False,
            },
        ),
    ]
