# Generated by Django 5.0.2 on 2024-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRepresentativeProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'models_collect_companyrepresentativeprofile',
                'managed': False,
            },
        ),
    ]
